In [1]:
import pandas as pd

### This notebook combines and cleans the comments, threads, and coded data from each of the three subreddits

In [2]:
# object for columns to open 
columns = ["submission_id", "body", "score", "year", "month"]

In [10]:
dcforrent_comments = pd.read_csv("../../data/reddit/original_scraped_data/DCforrent_12_5_comments.csv")
washdc_comments = pd.read_csv("../../data/reddit/original_scraped_data/washdc_12_5_comments.csv")
washingtondc_comments = pd.read_csv("../../data/reddit/original_scraped_data/washingtondc_12_5_comments.csv")

dcforrent_threads = pd.read_csv("../../data/reddit/original_scraped_data/DCforrent_12_5_threads.csv")
washdc_threads = pd.read_csv("../../data/reddit/original_scraped_data/washdc_12_5_threads.csv")
washingtondc_threads = pd.read_csv("../../data/reddit/original_scraped_data/washingtondc_12_5_threads.csv")

#dcforrent_coded = pd.read_csv("./data/reddit/DCforrent_comments_with_commentid_CODED_SET.csv")
#washdc_coded = pd.read_csv("./data/reddit/washdc_comments_with_commentid_CODED_SET.csv")
#washingtondc_coded = pd.read_csv("./data/reddit/washingtondc_comments_with_commentid_CODED_SET.csv")

In [13]:
len(dcforrent_comments) + len(washdc_comments) + len(washingtondc_comments)

32036

In [14]:
len(dcforrent_threads) + len(washdc_threads) + len(washingtondc_threads)

464

In [27]:
# add columns identifying subreddit and type (thread/comment) to each df

dcforrent_comments["subreddit"] = 0
washdc_comments["subreddit"] = 1
washingtondc_comments["subreddit"] = 2

dcforrent_comments["type"] = 1
washdc_comments["type"] = 1
washingtondc_comments["type"] = 1

dcforrent_threads["subreddit"] = 0
washdc_threads["subreddit"] = 1
washingtondc_threads["subreddit"] = 2

dcforrent_threads["type"] = 0
washdc_threads["type"] = 0
washingtondc_threads["type"] = 0

### Merge Dataframes

In [28]:
comments_df = pd.concat([dcforrent_comments, washdc_comments,washingtondc_comments])
comments_df

,comment_id,submission_id,author,body,score,year,month,subreddit,type
0,isl1exn,y57cbw,eeek0711,Or Cleveland Park in DC,4,2022,10,0,1
1,isl1dig,y57cbw,eeek0711,Takoma Park MD,3,2022,10,0,1
2,islh5rt,y57cbw,nonmimeticform,Baltimore,3,2022,10,0,1
3,isuelis,y57cbw,dcgirlsmallworld,If you are looking for a quiet neighborhood wi...,3,2022,10,0,1
4,isl1grp,y57cbw,eeek0711,I lived in the DeLano Apartments in Woodley Pa...,2,2022,10,0,1
...,...,...,...,...,...,...,...,...,...
22966,h9vbsnq,p90h2e,NaN,[deleted],1,2021,8,2,1
22967,ha1ypp5,p90h2e,CaptainObvious110,Hmm actually you make a lot of sense here. Th...,1,2021,8,2,1
22968,h9vcebj,p90h2e,129za,You probably know if better than I do. In the ...,1,2021,8,2,1
22969,h9vkj9w,p90h2e,NaN,[deleted],-1,2021,8,2,1
22970,h9wgxti,p90h2e,129za,Let’s be real - if I worked in CH real estate ...,2,2021,8,2,1

In [29]:
threads_df = pd.concat([dcforrent_threads, washdc_threads,washingtondc_threads])
threads_df.head()

,submission_id,title,text,year,month,subreddit,type
0,y57cbw,"Best quiet, safe but lively neighborhood in DC",I am in my late 30s and haven't lived in DC si...,2022,10,0,0
1,utr8aw,What Neighborhoods in DC/Mayland Should Be Avo...,NaN,2022,5,0,0
2,32cqd6,Recommendations on safe neighborhoods for a yo...,I'm moving to DC from the South in a few weeks...,2015,4,0,0
3,20t3z6,Find out how safe the neighborhood you want to...,NaN,2014,3,0,0
4,1h3ldb4,1 Month of Free Rent in 770 SQFT. High Rise Ap...,Apartment Takeover Opportunity: Market House i...,2024,11,0,0

In [30]:
coded_df = pd.concat([dcforrent_coded,washdc_coded,washingtondc_coded])
coded_df.head()

,Unnamed: 0,comment_id,submission_id,author,body,score,year,month,safety_code
0,0,isl1dig,y57cbw,eeek0711,Takoma Park MD,3,2022,10,0
1,1,i9cnmct,utr8aw,dans_cafe,"Generally speaking, robberies and muggings are...",1,2022,5,1
2,2,i9csov5,utr8aw,Ok_Priority_1534,Downtown/Central DC.\n\nAs I'm looking at diff...,1,2022,5,1
3,3,k7632z8,17ed6rg,Musictravels23,Hey there!! I have a fuIIy furnished sunny spa...,1,2023,10,0
4,4,io5bcjq,xciciq,cheesyuser,Thats a difficult ask. The 2000 range may be d...,2,2022,9,0

### Clean Threads

In [31]:
threads_df[threads_df["text"].isna()]

,submission_id,title,text,year,month,subreddit,type
1,utr8aw,What Neighborhoods in DC/Mayland Should Be Avo...,NaN,2022,5,0,0
3,20t3z6,Find out how safe the neighborhood you want to...,NaN,2014,3,0,0
0,1h2wunn,Why are criminals and violent teens allowed to...,NaN,2024,11,1,0
1,1gghbb2,Mob attack on U Street investigated as hate crime,NaN,2024,10,1,0
2,1go926g,Criminals have all out brawl on typical night ...,NaN,2024,11,1,0
...,...,...,...,...,...,...,...
211,1g68cl3,Someone get WMATA a Windows upgrade,NaN,2024,10,2,0
213,28ab08,Officer in Popville comments section blames re...,NaN,2014,6,2,0
215,11nf3e0,"More than 3 in 4 D.C. residents feel safe, Pos...",NaN,2023,3,2,0
219,k03gu6,A D.C. Council committee approved a bill Monda...,NaN,2020,11,2,0
221,10p64o,Fishing the Forgotten River in the Nation’s Ca...,NaN,2012,9,2,0

In [32]:
threads_df = threads_df.dropna(subset=["text"])

In [33]:
threads_df[threads_df["text"].isna()]

Empty DataFrame
Columns: [submission_id, title, text, year, month, subreddit, type]
Index: []

### Clean Comments

In [34]:
comments_df = comments_df.drop(comments_df[comments_df["body"]=="[removed]"].index)
comments_df = comments_df.drop(comments_df[comments_df["body"]=="[deleted]"].index)

In [35]:
comments_df

,comment_id,submission_id,author,body,score,year,month,subreddit,type
0,isl1exn,y57cbw,eeek0711,Or Cleveland Park in DC,4,2022,10,0,1
1,isl1dig,y57cbw,eeek0711,Takoma Park MD,3,2022,10,0,1
2,islh5rt,y57cbw,nonmimeticform,Baltimore,3,2022,10,0,1
3,isuelis,y57cbw,dcgirlsmallworld,If you are looking for a quiet neighborhood wi...,3,2022,10,0,1
4,isl1grp,y57cbw,eeek0711,I lived in the DeLano Apartments in Woodley Pa...,2,2022,10,0,1
...,...,...,...,...,...,...,...,...,...
22964,ha3j70q,p90h2e,129za,Fair enough !!,2,2021,8,2,1
22965,h9vcjfs,p90h2e,129za,Apartment complexes offer security for people ...,6,2021,8,2,1
22967,ha1ypp5,p90h2e,CaptainObvious110,Hmm actually you make a lot of sense here. Th...,1,2021,8,2,1
22968,h9vcebj,p90h2e,129za,You probably know if better than I do. In the ...,1,2021,8,2,1
22970,h9wgxti,p90h2e,129za,Let’s be real - if I worked in CH real estate ...,2,2021,8,2,1

### Save

In [ ]:
#comments_df.to_csv("./data/reddit/comments_ALL_12_6.csv")
#threads_df.to_csv("./data/reddit/threads_ALL_12_6.csv")
#coded_df.to_csv("./data/reddit/coded_comment_test_set_12_6.csv")